# Generated by Django 5.1.4 on 2024-12-13 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('38e59adb-fea0-472b-af11-a176e364f33f'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('logo', models.ImageField(upload_to='image/motive/logo')),
                ('motive_type', models.CharField(choices=[('Social Cause', 'Social Cause'), ('Environmental', 'Environmental'), ('Educational', 'Educational'), ('Medical', 'Medical'), ('Charity', 'Charity'), ('Other', 'Other')], default='Social Cause', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('53c2d055-8a9f-40c6-82a6-e04a984fce90'), primary_key=True, serialize=False)),
                ('dp', models.ImageField(upload_to='image/group/dp/')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.motive')),
            ],
        ),
        migrations.CreateModel(
            name='InitiatorGroupContributor',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('51eeedfa-f2b3-4692-9887-153324ea00c0'), primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Creator', 'Creator'), ('User', 'User')], default='User', max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.group')),
                ('motive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='community.motive')),
            ],
            options={
                'unique_together': {('contributor', 'group')},
            },
        ),
        migrations.CreateModel(
            name='groupContributor',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('f3f7afb9-9daf-4f05-8769-0de8ff1ff3bf'), primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Creator', 'Creator'), ('User', 'User')], default='User', max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.group')),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.motive')),
            ],
            options={
                'unique_together': {('contributor', 'group')},
            },
        ),
    ]
