# Generated by Django 5.1.4 on 2024-12-13 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('696261ca-55e7-4d97-9602-be98e0b98663'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupcontributor',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('62ac66fb-6b14-4c93-bb79-aa426ea598c1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='initiatorgroupcontributor',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('55a817f7-27d9-4016-b024-d011ef5902d0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motive',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
